<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Offres;
use Doctrine\ORM\Mapping;

/**
 * OffresRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OffresRepository extends \Doctrine\ORM\EntityRepository
{

}
